include_guard(GLOBAL)

# 把 vars=a:key,b:key2 转成 a=key|b=key2，C++ 侧按 | 切分
function(nyx_auth_vars out_name value)
    set(entries_text "${value}")
    string(REPLACE "," ";" entries "${entries_text}")
    set(pairs)
    foreach(entry IN LISTS entries)
        string(STRIP "${entry}" entry)
        if(entry STREQUAL "")
            continue()
        endif()

        string(FIND "${entry}" ":" split)
        if(split LESS 0)
            string(FIND "${entry}" "=" split)
        endif()
        if(split LESS 0)
            message(FATAL_ERROR "Invalid auth vars entry: ${entry}")
        endif()

        string(SUBSTRING "${entry}" 0 ${split} alias)
        math(EXPR key_start "${split} + 1")
        string(SUBSTRING "${entry}" ${key_start} -1 remote_key)
        string(STRIP "${alias}" alias)
        string(STRIP "${remote_key}" remote_key)
        if(alias STREQUAL "" OR remote_key STREQUAL "")
            message(FATAL_ERROR "Invalid auth vars entry: ${entry}")
        endif()

        list(APPEND pairs "${alias}=${remote_key}")
    endforeach()

    if(pairs)
        string(JOIN "|" result ${pairs})
    else()
        set(result "")
    endif()
    set(${out_name} "${result}" PARENT_SCOPE)
endfunction()

# 读取 WY 鉴权配置，并转换成 C++ 编译期宏
function(nyx_apply_wy_auth_properties target_name file_path)
    nyx_property(provider "${file_path}" "provider" "wy")
    string(TOLOWER "${provider}" provider)
    if(NOT provider STREQUAL "wy")
        message(FATAL_ERROR "Unsupported auth provider '${provider}' in ${file_path}")
    endif()

    nyx_property(auth_host "${file_path}" "host" "")
    nyx_property(auth_path_prefix "${file_path}" "pathPrefix" "")
    nyx_required_property(auth_api_token "${file_path}" "apiToken")
    nyx_required_property(auth_app_key "${file_path}" "appKey")
    nyx_required_property(auth_rc4_key "${file_path}" "rc4Key")
    nyx_required_property(auth_login_call_id "${file_path}" "loginCallId")
    nyx_property(auth_login_success_code "${file_path}" "loginSuccessCode" "0")
    nyx_required_property(auth_heartbeat_call_id "${file_path}" "heartbeatCallId")
    nyx_property(auth_heartbeat_success_code "${file_path}" "heartbeatSuccessCode" "0")
    nyx_required_property(auth_var_call_id "${file_path}" "varCallId")
    nyx_property(auth_var_success_code "${file_path}" "varSuccessCode" "0")
    nyx_property(auth_notice_call_id "${file_path}" "noticeCallId" "")
    nyx_property(auth_notice_success_code "${file_path}" "noticeSuccessCode" "0")
    nyx_property(auth_update_call_id "${file_path}" "updateCallId" "")
    nyx_property(auth_update_success_code "${file_path}" "updateSuccessCode" "0")
    nyx_property(auth_login_check_kind "${file_path}" "loginCheckKind" "0")
    nyx_property(auth_heartbeat_check_kind "${file_path}" "heartbeatCheckKind" "2")
    nyx_property(auth_var_check_kind "${file_path}" "varCheckKind" "2")
    nyx_required_property(auth_salt "${file_path}" "salt")
    nyx_required_property(auth_alphabet "${file_path}" "alphabet")
    nyx_property(auth_license_field "${file_path}" "licenseField" "")
    nyx_property(auth_device_field "${file_path}" "deviceField" "")
    nyx_property(auth_token_field "${file_path}" "tokenField" "")
    nyx_property(auth_time_field "${file_path}" "timeField" "")
    nyx_property(auth_sign_field "${file_path}" "signField" "")
    nyx_property(auth_nonce_field "${file_path}" "nonceField" "")
    nyx_property(auth_var_field "${file_path}" "varField" "")
    nyx_property(auth_vars "${file_path}" "vars" "")
    nyx_auth_vars(auth_vars_text "${auth_vars}")

    # 字段名和 call id 都来自配置，C++ 侧只负责按宏生成请求
    nyx_string_definition("${target_name}" NYX_AUTH_WY_HOST "${auth_host}")
    nyx_string_definition("${target_name}" NYX_AUTH_WY_PATH_PREFIX "${auth_path_prefix}")
    nyx_string_definition("${target_name}" NYX_AUTH_WY_API_TOKEN "${auth_api_token}")
    nyx_string_definition("${target_name}" NYX_AUTH_WY_APP_KEY "${auth_app_key}")
    nyx_string_definition("${target_name}" NYX_AUTH_WY_LOGIN_CALL_ID "${auth_login_call_id}")
    nyx_int_definition("${target_name}" NYX_AUTH_WY_LOGIN_SUCCESS_CODE "${auth_login_success_code}")
    nyx_string_definition("${target_name}" NYX_AUTH_WY_HEARTBEAT_CALL_ID "${auth_heartbeat_call_id}")
    nyx_int_definition("${target_name}" NYX_AUTH_WY_HEARTBEAT_SUCCESS_CODE "${auth_heartbeat_success_code}")
    nyx_string_definition("${target_name}" NYX_AUTH_WY_VAR_CALL_ID "${auth_var_call_id}")
    nyx_int_definition("${target_name}" NYX_AUTH_WY_VAR_SUCCESS_CODE "${auth_var_success_code}")
    nyx_string_definition("${target_name}" NYX_AUTH_WY_NOTICE_CALL_ID "${auth_notice_call_id}")
    nyx_int_definition("${target_name}" NYX_AUTH_WY_NOTICE_SUCCESS_CODE "${auth_notice_success_code}")
    nyx_string_definition("${target_name}" NYX_AUTH_WY_UPDATE_CALL_ID "${auth_update_call_id}")
    nyx_int_definition("${target_name}" NYX_AUTH_WY_UPDATE_SUCCESS_CODE "${auth_update_success_code}")
    nyx_int_definition("${target_name}" NYX_AUTH_WY_LOGIN_CHECK_KIND "${auth_login_check_kind}")
    nyx_int_definition("${target_name}" NYX_AUTH_WY_HEARTBEAT_CHECK_KIND "${auth_heartbeat_check_kind}")
    nyx_int_definition("${target_name}" NYX_AUTH_WY_VAR_CHECK_KIND "${auth_var_check_kind}")
    nyx_string_definition("${target_name}" NYX_AUTH_WY_SALT "${auth_salt}")
    nyx_string_definition("${target_name}" NYX_AUTH_WY_RC4_KEY "${auth_rc4_key}")
    nyx_string_definition("${target_name}" NYX_AUTH_WY_ALPHABET "${auth_alphabet}")
    nyx_string_definition("${target_name}" NYX_AUTH_WY_LICENSE_FIELD "${auth_license_field}")
    nyx_string_definition("${target_name}" NYX_AUTH_WY_DEVICE_FIELD "${auth_device_field}")
    nyx_string_definition("${target_name}" NYX_AUTH_WY_TOKEN_FIELD "${auth_token_field}")
    nyx_string_definition("${target_name}" NYX_AUTH_WY_TIME_FIELD "${auth_time_field}")
    nyx_string_definition("${target_name}" NYX_AUTH_WY_SIGN_FIELD "${auth_sign_field}")
    nyx_string_definition("${target_name}" NYX_AUTH_WY_NONCE_FIELD "${auth_nonce_field}")
    nyx_string_definition("${target_name}" NYX_AUTH_WY_VAR_FIELD "${auth_var_field}")
    nyx_string_definition("${target_name}" NYX_AUTH_WY_VARS "${auth_vars_text}")
endfunction()
